name: myPackage
version: 2.12.2
description: How to use packages in dart
author: Rabie
repository: https://github.com/rabieAlarini/dart_course
environment:
  sdk: '>=2.10.0 <3.0.0'
dependencies:
  english_words: ^4.0.0
  # in terminal write : pub get
